apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: the127terminal/ocrapp:latest
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URI
              value: "mongodb://mongo:27017/testdb"  # Update with your MongoDB URI
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer  # Change to 'NodePort' or 'ClusterIP' based on your needs

